SELECT city.name,country.name,country.region
FROM cities AS city
INNER JOIN countries AS country
ON city.country_code = country.code;

SELECT CITY.NAME AS CITY, COUNTRY.NAME AS COUNTRY, COUNTRY.REGION
FROM CITIES AS CITY
INNER JOIN COUNTRIES AS COUNTRY
ON CITY.COUNTRY_CODE = COUNTRY.CODE;

SELECT C.CODE AS COUNTRY_CODE, NAME,INFLATION_RATE, YEAR
FROM COUNTRIES AS C
INNER JOIN ECONOMIES AS E
ON C.CODE=E.CODE;

SELECT C.CODE AS CODE, NAME, REGION, YEAR, FERTILITY_RATE
FROM COUNTRIES AS C
INNER JOIN POPULATIONS AS P
ON C.CODE=P.COUNTRY_CODE